package com.snofed.publicapp.utils

object SharedPreferenceKeys {
    const val FIRST_TIME_LAUNCHED = "FIRST_TIME_LAUNCHED"
    const val SELECTED_LANGUAGE = "SELECTED_LANGUAGE"
    const val IS_USER_LOGGED_IN = "IS_USER_LOGGED_IN"
    const val IS_GUEST_LOGGED_IN = "IS_GUEST_LOGGED_IN"
    const val FIREBASE_TOKEN = "FIREBASE_TOKEN"
    const val IS_CREDENTIAL_REMEMBER_CB= "IS_CREDENTIAL_REMEMBER_CB"
    const val USER_EMAIL_ID= "USER_EMAIL_ID"
    const val USER_START_DATE= "USER_START_DATE"
    const val MOBILE= "MOBILE"
    const val USER_TOKEN = "token"
    const val USER_FIRST_NAME = "fullName"
    const val USER_LAST_NAME = "lastName"
    const val USER_USER_AGE = "AGE"
    const val USER_USER_WEIGHT = "WEIGHT"
    const val USER_GENDER_TYPE = "GENDER"
    const val USER_USER_ID = "id"
    const val CLUB_CLIENT_ID = "clientId"
    const val CLUB_TRAILS_ID = "trailId"
    const val CLUB_PUBLIC_ID = "feedId"
    const val CLUB_DESC = "description"
    const val PREFS_TOKEN_FILE = "prefs_token_file"
}